In [1]:
from sklearn.datasets import load_iris
iris_data = load_iris()

In [4]:
print("keys of iris dataset: {}".format(iris_data.keys()))

keys of iris dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
print(iris_data['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive 
...


In [5]:
print("Target names: {}".format(iris_data['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


In [6]:
print("Features: {}".format(iris_data['feature_names']))

Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print("Type of data: {}".format(type(iris_data['data'])))

Type of data: <class 'numpy.ndarray'>


In [ ]:
#shape =  No. of samples * No. of features
print("Shape of data: {}".format(iris_data['data'].shape))

Shape of data: (150, 4)


In [ ]:
print("First 5 data entries: \n{}".format(iris_data['data'][:5]))

First 5 data entries: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
print("Target: {}".format(iris_data['target']))
print("Type of target: {}".format(type(iris_data['target'])))

#here, 0 = setosa, 1 = versicolor, 2 = virginica

Target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Type of target: <class 'numpy.ndarray'>


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data['data'], iris_data['target'], random_state=0)

In [ ]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

"""
X_train: Contains 75% of the feature data (the input variables/measurements) for training

X_test: Contains 25% of the feature data for testing

y_train: Contains the corresponding 75% of the target values (labels/classes) for training

y_test: Contains the corresponding 25% of the target values for testing

For the Iris dataset specifically:

iris_data['data'] contains the features (sepal length, sepal width, petal length, petal width)

iris_data['target'] contains the labels (0 for setosa, 1 for versicolor, 2 for virginica)

"""

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)
